### PR TITLE
Fix image caption text contrast

### PR DESCRIPTION
**Pull request by guidorota**
This commit changes the colour of caption text to Base Light to provide more contrast with the dark background.

### CODE REVIEW

**Comment by guidorota** [comment]
Hi @madrilene , I recently started using your template and noticed that image captions don't have enough contrast with the backdrop when maximized.

I fixed the issue in my website and wanted to contribute back here.

**Comment by madrilene** [comment]
Ah ok, I'll look into that! We have to modify that still, as now the caption disappears in light mode on regular images.

**Comment by guidorota** [comment]
@madrilene could you point me to a page where I can reproduce the text disappearing in light mode? I tried to search for it but couldn't find one, even in light mode it seems that the backdrop is always dark enough to go well with `--color-base-light`.

**Comment by madrilene** [comment]
Sure! The regular caption is here (not within a dialog)

image

**Comment by guidorota** [comment]
Thanks for the pointer.

I updated the branch with a different selector that targets only the caption in the gallery.

**Review by madrilene — APPROVED** [review]

**Pull request merged**
